### ISSUE TITLE
Please use the json feed instead of scraping

### ISSUE THREAD

**Issue by probonopd** [michaeldelago/aipm#1]
Hey @michaeldelago, thanks for making this tool.

https://github.com/michaeldelago/aipm/blob/9b8b471cf2c4818b7dc43b02c0f86d71a9a2c78b/aipm/appimagelibrary.py#L129

Did you know that we are providing a JSON feed specifically for this purpose so that you don't have to scrape?

https://appimage.github.io/feed.json

Please use this instead, will make your life much easier!

**Comment by michaeldelago** [comment]
Hey! 

I didn't know this existed, haha. I've never been good at researching ;)

In my own (weak) defense, one of the points of my project was to have a meaningful exercise in web scraping. 

I should have a patch to use the proper JSON feed within the week (and likely before)

Thanks.

**Comment by michaeldelago** [comment]
Fixed in latest commit. 

> https://github.com/michaeldelago/aipm/blob/master/aipm/appimagelibrary.py#L152
